# -*- coding: utf-8 -*-
"""PhishGuard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1foagsOwL9_px48v4JRjeLoKI6XJ8pe2G
"""

import re
import warnings
import pandas as pd
import matplotlib.pyplot as plt
from urllib.parse import urlparse
import json
import joblib
import os
import kagglehub
warnings.filterwarnings('ignore')

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

!fusermount -uz /content/drive
!rm -rf /content/drive
!mkdir /content/drive
from google.colab import drive
drive.mount('/content/drive')
!ls /content/drive/MyDrive

brands = ["Nike", "Adidas", "Puma", "Apple", "Samsung", "Linkedin", "Facebook", "Google", "Whatsapp", "Instagram", "Paypal"]
BRANDS = brands
with open('/content/drive/My Drive/Colab files/brands.txt', 'w') as f:
    for brand in brands:
        f.write(brand + "\n")
f.close()
print("File Created.")

"""KAGGLE DATASET"""

path = kagglehub.dataset_download("taruntiwarihp/phishing-site-urls")
print("Path to dataset files:", path)

kaggle_dict = {
    "username": "nithinmanit",
    "key": "KGAT_1d2baca2e39f31924ca13989b6f46893"
}

with open("kaggle.json", "w") as f:
    json.dump(kaggle_dict, f)

files = os.listdir(path)
print(files)

df = pd.read_csv(path + "/phishing_site_urls.csv")
print(df.head())
print("Shape:", df.shape)
print("\nColumns:", df.columns.tolist())
print("\nFirst row:\n", df.iloc[0])
print("\nLabel distribution:\n", df.iloc[:, -1].value_counts())

"""Pre Training"""

df = pd.read_csv(path + "/phishing_site_urls.csv")

def extract_features(url):
    try:
        up = urlparse(url if url.startswith('http') else 'http://' + url)
        domain = up.netloc
        return {
            'length'        : len(url),
            'has_ip'        : 1 if re.search(r"\d{1,3}(\.\d{1,3}){3}", domain) else 0,
            'num_dots'      : url.count('.'),
            'num_hyphens'   : url.count('-'),
            'num_at'        : 1 if '@' in url else 0,
            'has_https'     : 1 if up.scheme == 'https' else 0,
            'sus_words'     : sum(1 for w in ['login','verify','secure','update','bank','account'] if w in url.lower()),
            'num_subdomains': len(domain.split('.')) - 2,
            'sus_tld'       : 1 if domain.split('.')[-1].lower() in {'xyz','top','gq','tk','ml','cf','ga','click'} else 0,
            'long_str'      : 1 if re.search(r"[a-z0-9]{10,}", domain) else 0,
            'num_slashes'   : url.count('/'),
            'num_params'    : len(up.query.split('&')) if up.query else 0,
        }
    except:
        return None

features = df['URL'].apply(extract_features)
features = [f for f in features if f is not None]
features_df = pd.DataFrame(features)
features_df['label'] = df['Label'].map({'good': 0, 'bad': 1})
features_df.dropna(inplace=True)

print()
print(features_df.shape)
print(features_df.head())

"""Training"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

X = features_df.drop('label', axis=1)
y = features_df['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
model.fit(X_train, y_train)

y_probs = model.predict_proba(X_test)[:, 1]

threshold = 0.35
y_pred = (y_probs >= threshold).astype(int)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nDetailed report:\n", classification_report(y_test, y_pred))

"""Saving"""

import joblib
joblib.dump(model, '/content/drive/My Drive/Colab files/phishguard_model.pkl')
print("Model saved.")

"""Rules (manual)

"""

def scheme(url):
    if url.scheme != 'https':
      return (15, "Uses HTTP instead of HTTPS")
    return (0, None)

def urlLen(url):
    if len(url) > 75:
      return (10, f"Url is suspiciously long. {len(url)} characters.")
    return (0, None)

def susWords(url):
    sw = ['login', 'verify', 'secure', 'update', 'bank', 'account']
    found = [w for w in sw if w in url]
    if found:
      return (10, f"Suspicious words found: {', '.join(found)}")
    return (0, None)

def IP(d):
    if re.search(r"\d{1,3}(\.\d{1,3}){3}", d):
      return (25, "Url uses IP address as domain name")
    return (0, None)

def dotCheck(d):
    dots = len(re.findall(r"\.", d))
    if dots > 4:
      return (15, "Contains too many dots.")
    return (0, None)

def hyphen(d):
    hyphen = len(re.findall(r"\-", d))
    if hyphen > 3:
      return (15, "Contains too many hyphens.")
    return (0, None)

def at(d):
    if re.search(r"\@", d):
      return (20, "Url contains '@'.")
    return (0, None)

def tld(d):
    susTLD = {'xyz', 'top', 'gq', 'tk', 'ml', 'cf', 'ga', 'click', 'work', 'support'}
    tld = d.split('.')[-1].lower()
    if tld in susTLD:
      return (10, "Sus TLD")
    return (0, None)

def brandSpoof(u, d, brands= BRANDS):
    for brand in brands:
      if re.search(rf"{brand}", u.lower()) and not re.search(rf"{brand}", d):
        return (25, f"Brand name {brand} found in a different part")
    return (0, None)

def randStr(d):
    if re.search(r"[a-z0-9]{10,}", d):
      return (10, "Long random string detected")
    return (0, None)

def subdomainAbuse(d):
    parts = d.split('.')
    if len(parts) > 4:
        return (15, f"Suspicious number of subdomains ({len(parts)-2})")
    return (0, None)

"""Prediction, analysis and result."""

# Load the saved model once
model = joblib.load('/content/drive/My Drive/Colab files/phishguard_model.pkl')[0]


from urllib.parse import urlparse

with open('/content/drive/My Drive/Colab files/brands.txt', 'r') as f:
  BRANDS = [line.strip() for line in f]
f.close()


def ml_predict(url):
    features = extract_features(url)
    if features is None:
        return (0, None)
    import pandas as pd
    row = pd.DataFrame([features])
    prob = model.predict_proba(row)[0][1]  # probability of being phishing
    if prob >= 0.7:
        return (40, f"ML model flagged this as phishing ({int(prob*100)}% confidence)")
    elif prob >= 0.4:
        return (20, f"ML model finds this suspicious ({int(prob*100)}% confidence)")
    return (0, None)

def analyze(url):
    up = urlparse(url if url.startswith('http') else 'http://' + url)
    rules = [
        scheme(up),
        urlLen(url),
        susWords(url),
        IP(up.netloc),
        dotCheck(up.netloc),
        hyphen(up.netloc),
        at(up.netloc),
        tld(up.netloc),
        brandSpoof(url, up.netloc),
        subdomainAbuse(up.netloc),
        ml_predict(url),        # ← new
    ]
    score = 0
    flags = []
    for points, reason in rules:
        if reason:
            score += points
            flags.append((points, reason))
    return score, flags

def result(score):
    if score <= 20:   return "SAFE"
    elif score <= 50: return "SUSPICIOUS"
    else:             return "DANGEROUS"

def plot_analysis(url, flags, score):
    if not flags:
        print("No flags to visualize — URL appears clean.")
        return

    labels = [reason for _, reason in flags]
    values = [points for points, _ in flags]
    colors = ['#ff4444' if p >= 25 else '#ff9900' if p >= 15 else '#ffcc00' for p in values]

    fig, ax = plt.subplots(figsize=(10, max(3, len(flags) * 0.8)))
    bars = ax.barh(labels, values, color=colors, edgecolor='black', height=0.5)

    for bar, val in zip(bars, values):
        ax.text(bar.get_width() + 0.5, bar.get_y() + bar.get_height()/2,
                f'+{val}', va='center', fontweight='bold')

    verdict = result(score)
    ax.set_xlabel('Risk Points', fontsize=12)
    ax.set_title(f'PhishGuard Analysis\n{url}\n{verdict}  |  Total Score: {score}',
                 fontsize=12, fontweight='bold')
    ax.set_xlim(0, max(values) * 1.3)
    ax.invert_yaxis()
    plt.tight_layout()
    ax.set_title(f'PhishGuard Analysis\n{url}\n|  Total Score: {score}')
    plt.savefig('/content/drive/My Drive/Colab files/phishguard_result.png', dpi=150)
    plt.show()
    print("Chart saved.")

url = input("Enter URL: ")
score, flags = analyze(url)

print(f"\nPhishGuard Analysis — {url}")
print("─" * 50)
for points, reason in flags:
    print(f"  +{points:<4} {reason}")
print("─" * 50)
print(f"  Score : {score}")
print(f"  Result: {result(score)}")


plot_analysis(url, flags, score)